apiVersion: v1
kind: Service
metadata:
  name: db-cluster
spec:
  ports:
    - port: 5001
      targetPort: 5432 # without this it won't work. seems to be default value will be set same with port
  selector:
    app: postgres-app

---

apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "postgres-config"
  # namespace: "default"
  labels:
    app: "postgres-app"
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgrespw"


---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "db-deploy"
  # namespace: "default"
  labels:
    app: "postgres-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "postgres-app"
  template:
    metadata:
      labels:
        app: "postgres-app"
    spec:
      containers:
      - name: "postgres"
        image: "postgres:latest"
        imagePullPolicy: Never
        env:
        - name: "POSTGRES_DB"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_DB"
              name: "postgres-config"
        - name: "POSTGRES_USER"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_USER"
              name: "postgres-config"
        - name: "POSTGRES_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_PASSWORD"
              name: "postgres-config"
        ports:
          - containerPort: 5432
            name: postgres
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/db-data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi